site_name: Aerial Robotics Landscape
theme: readthedocs
repo_url: https://github.com/ROS-Aerial/aerial_robotic_landscape
edit_uri: blob/main/docs/

copyright: 'This website is information assembled with help of the ROS Aerial Robotics Community group. Analytics with no-cookie tracking with goatviewer.com'

nav:
- 'education_and_tutorial.md'
- 'aerial_vehicles.md'
- 'simulation.md'
- 'hardware.md'
- 'autopilots_suites.md'
- 'aerial_autonomy_stacks.md'
- 'middleware_and_drivers.md'
- 'message_standards.md'
- 'safety_management.md'

markdown_extensions:
- pymdownx.snippets:
    check_paths: true
- admonition

plugins:
    - search
    - git-revision-date-localized
